<script lang="ts">
    import {onMount} from "svelte";
    import browser from "webextension-polyfill";

    const countries = [
        ["AF", "AFG", "Afghanistan", "AFN"],
        ["AX", "ALA", "Åland Islands", "EUR"],
        ["AL", "ALB", "Albania", "ALL"],
        ["DZ", "DZA", "Algeria", "DZD"],
        ["AS", "ASM", "American Samoa", "USD"],
        ["AD", "AND", "Andorra", "EUR"],
        ["AO", "AGO", "Angola", "AOA"],
        ["AI", "AIA", "Anguilla", "XCD"],
        ["AQ", "ATA", "Antarctica", "ARS"],
        ["AG", "ATG", "Antigua and Barbuda", "XCD"],
        ["AR", "ARG", "Argentina", "ARS"],
        ["AM", "ARM", "Armenia", "AMD"],
        ["AW", "ABW", "Aruba", "AWG"],
        ["AU", "AUS", "Australia", "AUD"],
        ["AT", "AUT", "Austria", "EUR"],
        ["AZ", "AZE", "Azerbaijan", "AZN"],
        ["BS", "BHS", "Bahamas", "BSD"],
        ["BH", "BHR", "Bahrain", "BHD"],
        ["BD", "BGD", "Bangladesh", "BDT"],
        ["BB", "BRB", "Barbados", "BBD"],
        ["BY", "BLR", "Belarus", "BYN"],
        ["BE", "BEL", "Belgium", "EUR"],
        ["BZ", "BLZ", "Belize", "BZD"],
        ["BJ", "BEN", "Benin", "XOF"],
        ["BM", "BMU", "Bermuda", "BMD"],
        ["BT", "BTN", "Bhutan", "BTN"],
        ["BO", "BOL", "Bolivia (Plurinational State of)", "BOB"],
        ["BQ", "BES", "Bonaire, Sint Eustatius and Saba", "USD"],
        ["BA", "BIH", "Bosnia and Herzegovina", "BAM"],
        ["BW", "BWA", "Botswana", "BWP"],
        ["BV", "BVT", "Bouvet Island", "NOK"],
        ["BR", "BRA", "Brazil", "BRL"],
        ["IO", "IOT", "British Indian Ocean Territory", "GBP"],
        ["BN", "BRN", "Brunei Darussalam", "BND"],
        ["BG", "BGR", "Bulgaria", "BGN"],
        ["BF", "BFA", "Burkina Faso", "XOF"],
        ["BI", "BDI", "Burundi", "BIF"],
        ["CV", "CPV", "Cabo Verde", "CVE"],
        ["KH", "KHM", "Cambodia", "KHR"],
        ["CM", "CMR", "Cameroon", "XAF"],
        ["CA", "CAN", "Canada", "CAD"],
        ["KY", "CYM", "Cayman Islands", "KYD"],
        ["CF", "CAF", "Central African Republic", "XAF"],
        ["TD", "TCD", "Chad", "XAF"],
        ["CL", "CHL", "Chile", "CLP"],
        ["CN", "CHN", "China", "CNY"],
        ["CX", "CXR", "Christmas Island", "AUD"],
        ["CC", "CCK", "Cocos (Keeling) Islands", "AUD"],
        ["CO", "COL", "Colombia", "COP"],
        ["KM", "COM", "Comoros", "KMF"],
        ["CG", "COG", "Congo", "XAF"],
        ["CD", "COD", "Congo (Democratic Republic of the)", "CDF"],
        ["CK", "COK", "Cook Islands", "NZD"],
        ["CR", "CRI", "Costa Rica", "CRC"],
        ["CI", "CIV", "Côte d'Ivoire", "XOF"],
        ["HR", "HRV", "Croatia", "HRK"],
        ["CU", "CUB", "Cuba", "CUC"],
        ["CW", "CUW", "Curaçao", "ANG"],
        ["CY", "CYP", "Cyprus", "EUR"],
        ["CZ", "CZE", "Czechia", "CZK"],
        ["DK", "DNK", "Denmark", "DKK"],
        ["DJ", "DJI", "Djibouti", "DJF"],
        ["DM", "DMA", "Dominica", "XCD"],
        ["DO", "DOM", "Dominican Republic", "DOP"],
        ["EC", "ECU", "Ecuador", "USD"],
        ["EG", "EGY", "Egypt", "EGP"],
        ["SV", "SLV", "El Salvador", "USD"],
        ["GQ", "GNQ", "Equatorial Guinea", "XAF"],
        ["ER", "ERI", "Eritrea", "ERN"],
        ["EE", "EST", "Estonia", "EUR"],
        ["ET", "ETH", "Ethiopia", "ETB"],
        ["SZ", "SWZ", "Eswatini", "SZL"],
        ["FK", "FLK", "Falkland Islands (Malvinas)", "FKP"],
        ["FO", "FRO", "Faroe Islands", "DKK"],
        ["FJ", "FJI", "Fiji", "FJD"],
        ["FI", "FIN", "Finland", "EUR"],
        ["FR", "FRA", "France", "EUR"],
        ["GF", "GUF", "French Guiana", "EUR"],
        ["PF", "PYF", "French Polynesia", "XPF"],
        ["TF", "ATF", "French Southern Territories", "EUR"],
        ["GA", "GAB", "Gabon", "XAF"],
        ["GM", "GMB", "Gambia", "GMD"],
        ["GE", "GEO", "Georgia", "GEL"],
        ["DE", "DEU", "Germany", "EUR"],
        ["GH", "GHA", "Ghana", "GHS"],
        ["GI", "GIB", "Gibraltar", "GIP"],
        ["GR", "GRC", "Greece", "EUR"],
        ["GL", "GRL", "Greenland", "DKK"],
        ["GD", "GRD", "Grenada", "XCD"],
        ["GP", "GLP", "Guadeloupe", "EUR"],
        ["GU", "GUM", "Guam", "USD"],
        ["GT", "GTM", "Guatemala", "GTQ"],
        ["GG", "GGY", "Guernsey", "GBP"],
        ["GN", "GIN", "Guinea", "GNF"],
        ["GW", "GNB", "Guinea-Bissau", "XOF"],
        ["GY", "GUY", "Guyana", "GYD"],
        ["HT", "HTI", "Haiti", "HTG"],
        ["HM", "HMD", "Heard Island and McDonald Islands", "AUD"],
        ["VA", "VAT", "Holy See", "EUR"],
        ["HN", "HND", "Honduras", "HNL"],
        ["HK", "HKG", "Hong Kong", "HKD"],
        ["HU", "HUN", "Hungary", "HUF"],
        ["IS", "ISL", "Iceland", "ISK"],
        ["IN", "IND", "India", "INR"],
        ["ID", "IDN", "Indonesia", "IDR"],
        ["IR", "IRN", "Iran (Islamic Republic of)", "IRR"],
        ["IQ", "IRQ", "Iraq", "IQD"],
        ["IE", "IRL", "Ireland", "EUR"],
        ["IM", "IMN", "Isle of Man", "GBP"],
        ["IL", "ISR", "Israel", "ILS"],
        ["IT", "ITA", "Italy", "EUR"],
        ["JM", "JAM", "Jamaica", "JMD"],
        ["JP", "JPN", "Japan", "JPY"],
        ["JE", "JEY", "Jersey", "GBP"],
        ["JO", "JOR", "Jordan", "JOD"],
        ["KZ", "KAZ", "Kazakhstan", "KZT"],
        ["KE", "KEN", "Kenya", "KES"],
        ["KI", "KIR", "Kiribati", "AUD"],
        ["KP", "PRK", "Korea (Democratic People's Republic of)", "KPW"],
        ["KR", "KOR", "Korea (Republic of)", "KRW"],
        ["KW", "KWT", "Kuwait", "KWD"],
        ["KG", "KGZ", "Kyrgyzstan", "KGS"],
        ["LA", "LAO", "Lao People's Democratic Republic", "LAK"],
        ["LV", "LVA", "Latvia", "EUR"],
        ["LB", "LBN", "Lebanon", "LBP"],
        ["LS", "LSO", "Lesotho", "LSL"],
        ["LR", "LBR", "Liberia", "LRD"],
        ["LY", "LBY", "Libya", "LYD"],
        ["LI", "LIE", "Liechtenstein", "CHF"],
        ["LT", "LTU", "Lithuania", "EUR"],
        ["LU", "LUX", "Luxembourg", "EUR"],
        ["MO", "MAC", "Macao", "MOP"],
        ["MK", "MKD", "North Macedonia", "MKD"],
        ["MG", "MDG", "Madagascar", "MGA"],
        ["MW", "MWI", "Malawi", "MWK"],
        ["MY", "MYS", "Malaysia", "MYR"],
        ["MV", "MDV", "Maldives", "MVR"],
        ["ML", "MLI", "Mali", "XOF"],
        ["MT", "MLT", "Malta", "EUR"],
        ["MH", "MHL", "Marshall Islands", "USD"],
        ["MQ", "MTQ", "Martinique", "EUR"],
        ["MR", "MRT", "Mauritania", "MRO"],
        ["MU", "MUS", "Mauritius", "MUR"],
        ["YT", "MYT", "Mayotte", "EUR"],
        ["MX", "MEX", "Mexico", "MXN"],
        ["FM", "FSM", "Micronesia (Federated States of)", "USD"],
        ["MD", "MDA", "Moldova (Republic of)", "MDL"],
        ["MC", "MCO", "Monaco", "EUR"],
        ["MN", "MNG", "Mongolia", "MNT"],
        ["ME", "MNE", "Montenegro", "EUR"],
        ["MS", "MSR", "Montserrat", "XCD"],
        ["MA", "MAR", "Morocco", "MAD"],
        ["MZ", "MOZ", "Mozambique", "MZN"],
        ["MM", "MMR", "Myanmar", "MMK"],
        ["NA", "NAM", "Namibia", "NAD"],
        ["NR", "NRU", "Nauru", "AUD"],
        ["NP", "NPL", "Nepal", "NPR"],
        ["NL", "NLD", "Netherlands", "EUR"],
        ["NC", "NCL", "New Caledonia", "XPF"],
        ["NZ", "NZL", "New Zealand", "NZD"],
        ["NI", "NIC", "Nicaragua", "NIO"],
        ["NE", "NER", "Niger", "XOF"],
        ["NG", "NGA", "Nigeria", "NGN"],
        ["NU", "NIU", "Niue", "NZD"],
        ["NF", "NFK", "Norfolk Island", "AUD"],
        ["MP", "MNP", "Northern Mariana Islands", "USD"],
        ["NO", "NOR", "Norway", "NOK"],
        ["OM", "OMN", "Oman", "OMR"],
        ["PK", "PAK", "Pakistan", "PKR"],
        ["PW", "PLW", "Palau", "USD"],
        ["PS", "PSE", "Palestine, State of", "ILS"],
        ["PA", "PAN", "Panama", "PAB"],
        ["PG", "PNG", "Papua New Guinea", "PGK"],
        ["PY", "PRY", "Paraguay", "PYG"],
        ["PE", "PER", "Peru", "PEN"],
        ["PH", "PHL", "Philippines", "PHP"],
        ["PN", "PCN", "Pitcairn", "NZD"],
        ["PL", "POL", "Poland", "PLN"],
        ["PT", "PRT", "Portugal", "EUR"],
        ["PR", "PRI", "Puerto Rico", "USD"],
        ["QA", "QAT", "Qatar", "QAR"],
        ["RE", "REU", "Réunion", "EUR"],
        ["RO", "ROU", "Romania", "RON"],
        ["RU", "RUS", "Russian Federation", "RUB"],
        ["RW", "RWA", "Rwanda", "RWF"],
        ["BL", "BLM", "Saint Barthélemy", "EUR"],
        ["SH", "SHN", "Saint Helena, Ascension and Tristan da Cunha", "SHP"],
        ["KN", "KNA", "Saint Kitts and Nevis", "XCD"],
        ["LC", "LCA", "Saint Lucia", "XCD"],
        ["MF", "MAF", "Saint Martin (French part)", "EUR"],
        ["PM", "SPM", "Saint Pierre and Miquelon", "EUR"],
        ["VC", "VCT", "Saint Vincent and the Grenadines", "XCD"],
        ["WS", "WSM", "Samoa", "WST"],
        ["SM", "SMR", "San Marino", "EUR"],
        ["ST", "STP", "Sao Tome and Principe", "STD"],
        ["SA", "SAU", "Saudi Arabia", "SAR"],
        ["SN", "SEN", "Senegal", "XOF"],
        ["RS", "SRB", "Serbia", "RSD"],
        ["SC", "SYC", "Seychelles", "SCR"],
        ["SL", "SLE", "Sierra Leone", "SLL"],
        ["SG", "SGP", "Singapore", "SGD"],
        ["SX", "SXM", "Sint Maarten (Dutch part)", "ANG"],
        ["SK", "SVK", "Slovakia", "EUR"],
        ["SI", "SVN", "Slovenia", "EUR"],
        ["SB", "SLB", "Solomon Islands", "SBD"],
        ["SO", "SOM", "Somalia", "SOS"],
        ["ZA", "ZAF", "South Africa", "ZAR"],
        ["GS", "SGS", "South Georgia and the South Sandwich Islands", "GBP"],
        ["SS", "SSD", "South Sudan", "SSP"],
        ["ES", "ESP", "Spain", "EUR"],
        ["LK", "LKA", "Sri Lanka", "LKR"],
        ["SD", "SDN", "Sudan", "SDG"],
        ["SR", "SUR", "Suriname", "SRD"],
        ["SJ", "SJM", "Svalbard and Jan Mayen", "NOK"],
        ["SE", "SWE", "Sweden", "SEK"],
        ["CH", "CHE", "Switzerland", "CHF"],
        ["SY", "SYR", "Syrian Arab Republic", "SYP"],
        ["TW", "TWN", "Taiwan", "TWD"],
        ["TJ", "TJK", "Tajikistan", "TJS"],
        ["TZ", "TZA", "Tanzania, United Republic of", "TZS"],
        ["TH", "THA", "Thailand", "THB"],
        ["TL", "TLS", "Timor-Leste", "USD"],
        ["TG", "TGO", "Togo", "XOF"],
        ["TK", "TKL", "Tokelau", "NZD"],
        ["TO", "TON", "Tonga", "TOP"],
        ["TT", "TTO", "Trinidad and Tobago", "TTD"],
        ["TN", "TUN", "Tunisia", "TND"],
        ["TR", "TUR", "Turkey", "TRY"],
        ["TM", "TKM", "Turkmenistan", "TMT"],
        ["TC", "TCA", "Turks and Caicos Islands", "USD"],
        ["TV", "TUV", "Tuvalu", "AUD"],
        ["UG", "UGA", "Uganda", "UGX"],
        ["UA", "UKR", "Ukraine", "UAH"],
        ["AE", "ARE", "United Arab Emirates", "AED"],
        ["GB", "GBR", "United Kingdom of Great Britain and Northern Ireland", "GBP"],
        ["US", "USA", "United States of America", "USD"],
        ["UM", "UMI", "United States Minor Outlying Islands", "USD"],
        ["UY", "URY", "Uruguay", "UYU"],
        ["UZ", "UZB", "Uzbekistan", "UZS"],
        ["VU", "VUT", "Vanuatu", "VUV"],
        ["VE", "VEN", "Venezuela (Bolivarian Republic of)", "VEF"],
        ["VN", "VNM", "Viet Nam", "VND"],
        ["VG", "VGB", "Virgin Islands (British)", "USD"],
        ["VI", "VIR", "Virgin Islands (U.S.)", "USD"],
        ["WF", "WLF", "Wallis and Futuna", "XPF"],
        ["EH", "ESH", "Western Sahara", "MAD"],
        ["YE", "YEM", "Yemen", "YER"],
        ["ZM", "ZMB", "Zambia", "ZMW"],
        ["ZW", "ZWE", "Zimbabwe", "BWP"],
    ];

    let country = "US";
    onMount(async () => {
        country = ((await browser.storage.local.get("country"))?.country ?? "US") as unknown as string;
    });

    function handleSelection(e: Event) {
        const selected = (<HTMLSelectElement>e.target).value;
        browser.storage.local.set({country: selected});
        browser.storage.session.clear();
    }
</script>


<div>
    <h1>Options</h1>
    <label>
        Country:
        <select on:change={handleSelection}>
            {#each countries as [code2, code3, name, currency]}
                <option value={code2} selected={code2 === country}>{name}</option>
            {/each}
        </select>
    </label>
</div>


<style>
    div {
        width: 600px;
        margin: 60px auto;
    }

    h1 {
        font-size: 32px;
        font-weight: normal;
    }

    label {
        font-size: 12px;
    }
</style>
